# Generated by Django 5.2.12 on 2026-03-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, unique=True),
        ),
    ]
